#include "InventoryWidget.h"
#include "ItemSlotWidget.h"
#include "Components/UniformGridPanel.h"
#include "Components/UniformGridSlot.h"
#include "Components/CanvasPanel.h" // ìº”ë²„ìŠ¤ íŒ¨ë„ ì¶”ê°€
#include "MainCharacter.h"
#include "UInventoryComponent.h"
#include "ItemDataAsset.h"


void UInventoryWidget::NativeConstruct()
{
	Super::NativeConstruct();

	ItemSlotWidgets.Empty();
	if (InventoryPanel)
	{
		InventoryPanel->ClearChildren();
	}

	if (CloseButton)
	{
		CloseButton->OnClicked.AddDynamic(this, &UInventoryWidget::OnCloseButtonClicked);
	}
}

void UInventoryWidget::RefreshInventory()
{
	if (!InventoryPanel || !ItemSlotClass || !InventoryRootPanel) return;

	InventoryPanel->ClearChildren();  // UI ì´ˆê¸°í™”
	ItemSlotWidgets.Empty();

	APlayerController* PC = GetWorld()->GetFirstPlayerController();
	AMainCharacter* MainCharacter = Cast<AMainCharacter>(PC->GetPawn());
	if (!MainCharacter || !MainCharacter->InventoryComponent) return;

	if (!MainCharacter) return;
	if (!MainCharacter->InventoryComponent) return;

	const TArray<UItemDataAsset*>& Items = MainCharacter->InventoryComponent->InventoryItems;
	const int32 MaxSlotCount = FMath::Max(6, Items.Num());

	for (int32 i = 0; i < MaxSlotCount; i++)
	{
		UItemSlotWidget* NewSlot = CreateWidget<UItemSlotWidget>(this, ItemSlotClass);
		if (!NewSlot) continue;

		if (Items.IsValidIndex(i) && Items[i])
		{
			NewSlot->SetItem(Items[i]);

		}
		else
		{
			NewSlot->ClearItem();
		}

		/*UUniformGridSlot* GridSlot = InventoryPanel->AddChildToUniformGrid(NewSlot);
		GridSlot->SetColumn(i % 3);
		GridSlot->SetRow(i / 3);*/

		InventoryPanel->AddChildToUniformGrid(NewSlot, i / 3, i % 3);
		ItemSlotWidgets.Add(NewSlot);

		/*ItemSlotWidgets.Add(NewSlot);*/
	}
}

void UInventoryWidget::OnCloseButtonClicked()
{
	SetVisibility(ESlateVisibility::Collapsed);  // âœ… RemoveFromParent() ì•„ë‹˜! ë‹¨ìˆœíˆ ìˆ¨ê¸°ëŠ” ê±¸ë¡œ!
	UE_LOG(LogTemp, Warning, TEXT("ì¸ë²¤í† ë¦¬ UI ë‹«ê¸°"));

	// ğŸ”½ ì»¤ì„œ ìˆ¨ê¸°ê¸° + ì…ë ¥ ëª¨ë“œ ë˜ëŒë¦¬ê¸°
	if (APlayerController* PC = GetOwningPlayer())
	{
		PC->bShowMouseCursor = false;

		FInputModeGameOnly GameInput;
		PC->SetInputMode(GameInput);

		UE_LOG(LogTemp, Warning, TEXT("ğŸ–±ï¸ ë§ˆìš°ìŠ¤ ì»¤ì„œ ë” + ì…ë ¥ëª¨ë“œ ê²Œì„ ì „ìš©ìœ¼ë¡œ ë³€ê²½"));
	}
}
