#include "UInventoryComponent.h"

void UInventoryComponent::BeginPlay()
{
	Super::BeginPlay();

    InventoryItems.Empty(); // âœ… í˜¹ì‹œë¼ë„ null ë“¤ì–´ê°€ ìˆì—ˆìœ¼ë©´ ì „ë¶€ ì œê±°
    InventoryWidget->RefreshInventory();
    InventoryItems.Init(nullptr, 6);
}

void UInventoryComponent::AddItem(UItemDataAsset* NewItem)
{
    //if (!NewItem)
    //{
    //    UE_LOG(LogTemp, Error, TEXT("âŒ AddItem ë°›ì€ NewItemì´ nullì…ë‹ˆë‹¤"));
    //    return; // nullì´ë©´ ë” ì´ìƒ ì§„í–‰ ì•ˆí•¨
    //}

    //if (NewItem && InventoryItems.Num() >= 6)
    //{
    //    UE_LOG(LogTemp, Warning, TEXT("âŒ ì¸ë²¤í† ë¦¬ ê°€ë“ì°¸ (ìµœëŒ€ 6ê°œ)"));
    //    return;
    //}
    //InventoryItems.Add(NewItem);
    //UE_LOG(LogTemp, Warning, TEXT("ì¸ë²¤í† ë¦¬ì— ì¶”ê°€ë¨: %s"), *NewItem->ItemName.ToString());
    //LogInventoryState();  // âœ… ì¶”ê°€

    //// í™”ë©´ì— ì¸ë²¤í† ë¦¬ì˜ ì „ì²´ ì•„ì´í…œ ëª©ë¡ì„ ì¶œë ¥
    //FString InventoryList;
    //for (UItemDataAsset* Item : InventoryItems)
    //{
    //    if (Item)
    //    {
    //        InventoryList += Item->ItemName.ToString() + TEXT("\n");
    //    }
    //}
    //   

    //    // ì „ì²´ ì•„ì´í…œì„ GEngineìœ¼ë¡œ í™”ë©´ì— ì¶œë ¥
    //    if (GEngine)
    //    {
    //        GEngine->AddOnScreenDebugMessage(-1, 5.f, FColor::Green, InventoryList);
    //    }

    //    if (InventoryWidget)
    //    {
    //        InventoryWidget->RefreshInventory();
    //    }
    
    if (!NewItem)
    {
        UE_LOG(LogTemp, Error, TEXT("âŒ AddItem ë°›ì€ NewItemì´ nullì…ë‹ˆë‹¤"));
        return;
    }

    // ì‹¤ì œ ì•„ì´í…œì´ ë“¤ì–´ìˆëŠ” ìŠ¬ë¡¯ ìˆ˜ ê³„ì‚°
    int32 UsedSlotCount = 0;
    for (UItemDataAsset* Item : InventoryItems)
    {
        if (Item != nullptr)
        {
            ++UsedSlotCount;
        }
    }

    // ê°€ë“ ì°¼ìœ¼ë©´ ì¶”ê°€ ê±°ë¶€
    if (UsedSlotCount >= InventoryItems.Num())
    {
        UE_LOG(LogTemp, Warning, TEXT("âŒ ì¸ë²¤í† ë¦¬ ê°€ë“ì°¸ (ì‹¤ì œ ì±„ì›Œì§„ ì•„ì´í…œ %dê°œ)"), UsedSlotCount);
        return;
    }

    // ë¹„ì–´ìˆëŠ” ìŠ¬ë¡¯ì— ì¶”ê°€
    int32 EmptyIndex = InventoryItems.Find(nullptr);
    if (EmptyIndex != INDEX_NONE)
    {
        InventoryItems[EmptyIndex] = NewItem;
        UE_LOG(LogTemp, Warning, TEXT("ì¸ë²¤í† ë¦¬ì— ì¶”ê°€ë¨: %s"), *NewItem->ItemName.ToString());
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("âŒ ë¹ˆ ìŠ¬ë¡¯ì„ ì°¾ì„ ìˆ˜ ì—†ìŒ"));
        return;
    }

    // ë””ë²„ê·¸ ì¶œë ¥
    LogInventoryState();

    // UI ì—…ë°ì´íŠ¸
    if (InventoryWidget)
    {
        InventoryWidget->RefreshInventory();
    }
}

void UInventoryComponent::SetInventoryWidget(UInventoryWidget* NewInventoryWidget)
{
    InventoryWidget = NewInventoryWidget;
}

void UInventoryComponent::LogInventoryState()
{

    UE_LOG(LogTemp, Warning, TEXT("ğŸ§© [ì¸ë²¤í† ë¦¬ ìƒíƒœ ì¶œë ¥] ì „ì²´ %dê°œ ìŠ¬ë¡¯:"), InventoryItems.Num());

    for (int32 i = 0; i < InventoryItems.Num(); ++i)
    {
        if (InventoryItems[i])
        {
            UE_LOG(LogTemp, Warning, TEXT("  â–¸ [%d] %s"), i, *InventoryItems[i]->ItemName.ToString());
        }
        else
        {
            UE_LOG(LogTemp, Warning, TEXT("  â–« [%d] (ë¹ˆ ìŠ¬ë¡¯)"), i);
        }
    }
}
